- name: Ansible test
  hosts: localhost
  tasks:
  - name: launching AWS instance using Ansible
    ec2:
      key_name: MyKeyPair
      instance_type: t2.micro
      image: ami-0a6b2839d44d781b2
      region: us-east-1
      wait: yes
      count: 1
      vpc_subnet_id: subnet-0344b160acfd6d05f
      group_id: "sg-05167866ea2b039de"
      instance_tags:
        Name: Test
      assign_public_ip: yes
      aws_access_key: "{{ AWS_ACCESS_KEY }}"
      aws_secret_key: "{{ AWS_SECRET_KEY }}"
